mp3val.exe: main.obj mpegparse.obj out.obj report.obj crossapi.obj crc.obj
	dmc main.obj mpegparse.obj out.obj report.obj crossapi.obj crc.obj user32.lib -omp3val.exe
main.obj: main.cpp
	dmc -c main.cpp
mpegparse.obj: mpegparse.cpp
	dmc -c mpegparse.cpp
out.obj: out.cpp
	dmc -c out.cpp
report.obj: report.cpp
	dmc -c report.cpp
crossapi.obj: crossapi.cpp
	dmc -c crossapi.cpp
crc.obj: crc.cpp crc.h
	dmc -c crc.cpp
clean:
	del *.exe
	del *.obj
	del *.map
