(function(){
var g=this;function h(a,b){var c=b||g;if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(d,e);return a.apply(c,d)}}else return function(){return a.apply(c,arguments)}};function i(a){this.a=a||{};this.pathname=window.location.pathname;this.c=true;if(this.a.tracklinks===false)this.c=false;if(this.a.trackQueryParams)this.i=true;if(!(a=this.a.cookiePath)){a=/^(.*\/)/.exec(this.pathname)[0];if(a=="/")a=this.pathname+"/";a=a}this.d=a;this.prefix=this.a.prefix||"";this.f=this.a.defaultEventName;this.e=this.a.defaultAction;this.g=this.a.defaultLabel;a=this.a.profile;var b=this.prefix+this.pathname;if(this.i)b+=window.location.search;window._gaq=window._gaq||[];window._gaq.push(["_setAccount",
a]);window._gaq.push(["_setCookiePath",this.d]);window._gaq.push(["_setAllowAnchor",true]);window._gaq.push(["_trackPageview",b]);if(!window._gat){a=document.createElement("script");a.type="text/javascript";a.async=true;a.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}j(this,this.h,this);this.a.trackUnload&&k(this,window,"unload",this.j,this)}
i.prototype.h=function(){if(this.c){for(var a=["a"],b=[],c=0,e=a.length;c<e;c++){var d=document.getElementsByTagName(a[c]);if(d){b.push(d);var f=0;for(e=d.length;f<e;f++)l(this,d[f])}}this.anchors=b}this.a.heatMapper&&m(this)};i.prototype.j=function(){this.b("AutoTrack: Navigation","Unload",window.location.href)};function m(a){k(a,document,"click",function(b){this.b("AutoTrack: Heatmap","Click",b.clientX+","+b.clientY)},a)}
i.prototype.b=function(a,b,c){if(window._gaq){if(this.prefix)c=this.prefix+c;window._gaq.push(["_trackEvent",a,b,c])}};
function n(a,b,c){function e(d){if(typeof d=="string")return d;else if(typeof d=="function")return d(c)}if(b=="eventname"){if(!(b=c.getAttribute("data-g-event"))){if(!(a=e(a.f)))a=c.tagName.toLowerCase()=="a"?c.hostname==window.location.hostname?"AutoTrack: Link Click":"AutoTrack: Outbound Click":"AutoTrack: Element Click";b=a}return b}else if(b=="action")return c.getAttribute("data-g-action")||e(a.e)||c.getAttribute("href")||"AutoTrack: Element Click";else if(b=="label")return c.getAttribute("data-g-label")||
e(a.g)||a.pathname}function l(a,b){k(a,b,"click",function(){var c=n(this,"eventname",b),e=n(this,"action",b),d=n(this,"label",b);this.b(c,e,d)},a)}function k(a,b,c,e,d){if(d)e=h(e,d);if(b.addEventListener)b.addEventListener(c,e,false);else if(b.attachEvent)return b.attachEvent("on"+c,e)}
function j(a,b,c){if(c)b=h(b,c);if(document.addEventListener)try{k(a,document,"DOMContentLoaded",b,a)}catch(e){k(a,window,"load",b,a)}else if(!document.uniqueID&&document.expando)var d=document.createElement("tempnode"),f=window.setInterval(function(){try{d.doScroll("left")}catch(r){return}window.clearInterval(f);f=d=null;if(c)b=h(b,c);b()},50);else if("readyState"in document)f=window.setInterval(function(){if(/loaded|complete/.test(document.readyState)){window.clearInterval(f);f=null;if(c)b=h(b,
c);b()}},50);else k(a,window,"load",b,a)}var o="gweb.analytics.AutoTrack".split("."),p=g;!(o[0]in p)&&p.execScript&&p.execScript("var "+o[0]);for(var q;o.length&&(q=o.shift());)if(!o.length&&i!==undefined)p[q]=i;else p=p[q]?p[q]:p[q]={};i.prototype.trackEvent=i.prototype.b;
})()