/*
 Homepage experience animation functionality.
 This file includes all functionality to render the countdown
 clock, and ball physics. Depends on box2d libraries and base.js.
 @author mking@mking.me (Matt King)
*/
var path_to_img = "./Google I O 2011_files/";
if(!window.requestAnimationFrame)window.requestAnimationFrame=function(){return window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(i){window.setTimeout(i,1E3/60)}}();
(function(){function i(a){this.opts=a;this.bounds=a.bounds;this.gravity=new b2Vec2(a.gravity.x,a.gravity.y);this.surface=a.surface;this.dots=a.dots;this.surfaces={};this.iterations=1;this.timeStep=0.05;this.opts.types={};for(a=0;a<this.opts.colors.length;a++){var d=this.opts.colors[a];d&&!this.opts.types[d]&&(this.opts.types[d]=t(d,this.opts.dotType,this.opts.ctx))}this.opts.types.c9c9c9=t("c9c9c9",this.opts.dotType,this.opts.ctx);this.opts.types.d9d9d9=t("d9d9d9",this.opts.dotType,this.opts.ctx);
this.opts.types.b6b4b5=t("b6b4b5",this.opts.dotType+" separator",this.opts.ctx);this.createWorld()}function u(a){this.x=a.x;this.y=a.y;this.ctx=a.ctx;this.matrix=a.matrix;this.num=a.num;this.blankColor=a.blankColor||"#d9d9d9";this.activeColor=a.activeColor;this.dots=[];for(a=0;a<this.matrix.length;a++)for(var d=0;d<this.matrix[a].length;d++)this.dots.push(new B({x:this.x+19*d,y:this.y+19*a,ctx:this.ctx,fillStyle:this.matrix[a][d]==1?this.activeColor:this.blankColor,willDraw:this.matrix[a][d]!=2,isActive:this.matrix[a][d]==
1,digit:this}))}function B(a){this.x=a.x;this.y=a.y;this.ctx=a.ctx;this.fillStyle=a.fillStyle;this.willDraw=a.willDraw;this.isActive=a.isActive;this.digit=a.digit}function q(a,d){return Math.round(Math.random()*(d-a))+a}function r(a){var d=0,e=0;do d+=a.offsetLeft,e+=a.offsetTop;while(a=a.offsetParent);return[d,e]}function C(){return[window.innerWidth||document.documentElement.clientWidth,window.innerHeight||document.documentElement.clientHeight]}function t(a,d,e){var b=new Image;b.className=d;b.src=
path_to_img+d.replace(/\s.*?$/,"")+"-"+a+".png";e.appendChild(b);return b}function v(a,d){a<100&&d==3&&(a="0"+a);a<10&&(a="0"+a);return a.toString()}function D(){var a=(new Date).getTime(),d=Math.floor((I-a)/1E3),a=v(Math.floor(d/86400),3),e=Math.floor(d%86400),d=v(Math.floor(e/3600),2),b=v(Math.floor(e%3600/60),2),e=v(e%3600%60%60,2),a=[a,d,b,e].join("").split("");a.splice(3,0,":");a.splice(6,0,":");a.splice(9,0,":");return a}function x(){var a=D(),d=0;n=[];for(var e=0;e<a.length;e++)l.length>
0&&a[e]==l[e].num?(n.push(l[e]),d+=a[e]==":"?36:94):(a[e]==":"?(n.push(new u({ctx:j,x:d,y:14,num:a[e],matrix:J,activeColor:"b6b4b5"})),d+=36):(n.push(new u({ctx:j,x:d,y:14,num:parseInt(a[e],0),matrix:s[parseInt(a[e],0)],activeColor:g.opts.colors[e],blankColor:e<4||e>9?"c9c9c9":"d9d9d9",successor:l.length?l[e]:null})),d+=94),n[e].draw(),l.length&&m.push(l[e]));g.step();for(a=0;a<m.length;a++)m[a].done?m.splice(a,1):(m[a].removed||m[a].remove(),m[a].draw());l=n;requestAnimationFrame(x)}function w(){var a=
q(-10,10),d=q(-10,10);o>40&&(a=q(-50,50));g.adjustGravity(a,d);o<40?setTimeout(w,q(2E3,4E3)):setTimeout(w,q(5E3,1E4))}i.prototype.createWorld=function(){var a=new b2AABB;a.minVertex.Set(-2E3,-2E3);a.maxVertex.Set(2E3,2E3);this.world=new b2World(a,this.gravity,!0);this.createGround((window.innerHeight||document.documentElement.clientHeight)-355);return this.world};i.prototype.createGround=function(a){if(this.ground)this.world.DestroyBody(this.ground),this.ground=null;var d=new b2BoxDef;d.extents.Set(2E3,
50);d.friction=0;d.restitution=0.9;var e=new b2BodyDef;e.AddShape(d);e.position.Set(0,a);this.ground=this.world.CreateBody(e)};i.prototype.createSurface=function(a,d,e,b,f,c){typeof c=="undefined"&&(c=!0);var g=new b2BoxDef;if(!c)g.density=this.surface.density;g.restitution=this.surface.restitution;g.friction=this.surface.friction;g.extents.Set(b,f);b=new b2BodyDef;b.AddShape(g);b.position.Set(d,e);this.surfaces[a]&&this.world.DestroyBody(this.surfaces[a]);this.surfaces[a]=this.world.CreateBody(b);
return this.surfaces[a]};i.prototype.createDot=function(a,d,e){var b=new b2CircleDef;b.density=this.dots.density;b.radius=7;b.restitution=this.dots.restitution;b.friction=this.dots.friction;var c=new b2BodyDef;c.AddShape(b);c.position.Set(a,d);c.linearVelocity.Set(Math.random()*e-e/2,Math.random()*e-e/2);return this.world.CreateBody(c)};i.prototype.destroyDot=function(a){this.world.DestroyBody(a)};i.prototype.adjustGravity=function(a,d){this.world.m_gravity=new b2Vec2(a,d)};i.prototype.unload=function(){for(k in this.surfaces)this.world.DestroyBody(this.surfaces[k]);
this.world.DestroyBody(this.ground);this.world=null};i.prototype.step=function(){this.world.Step(this.timeStep,this.iterations)};i.prototype.updateBounds=function(a){this.createGround(y[1]-355);this.bounds=a};u.prototype.draw=function(){if(this.dots.length===0)o-=this.removedDotCount,this.done=!0;else{for(var a=0;a<this.dots.length;a++)if(this.removed)if(!E&&this.dots[a].isActive&&!degraded){if(!this.dots[a].ball2d)this.dots[a].ball2d=g.createDot(this.dots[a].x,this.dots[a].y,this.velocity),this.dots[a].d.style.zIndex=
99;this.dots[a].x=this.dots[a].ball2d.m_position0.x;this.dots[a].y=this.dots[a].ball2d.m_position0.y;this.dots[a].y<-350||this.dots[a].x<g.bounds[0]*-1-20||this.dots[a].x>y[0]||o>K?(g.destroyDot(this.dots[a].ball2d),this.ctx.removeChild(this.dots[a].d),this.dots.splice(a,1),o--,this.removedDotCount--):this.dots[a].draw()}else this.ctx.removeChild(this.dots[a].d),this.dots.splice(a,1);else this.dots[a].draw();if(this.removed&&!this.removedDotCount)o+=this.dots.length,this.removedDotCount=this.dots.length}};
u.prototype.remove=function(){var a=s[this.num-1]||s[s.length-1],d=s[this.num];if(a&&(this.num!==0||this.num===1))for(var b=0,c=0;c<a.length;c++)for(var f=0;f<a[c].length;f++)d[c][f]==a[c][f]&&this.dots[b]&&(this.ctx.removeChild(this.dots[b].d),this.dots.splice(b,1),b--),b++;this.velocity=this.num===0?g.dots.highVelocity:g.dots.lowVelocity;this.removed=!0};B.prototype.draw=function(){if(this.willDraw){if(!this.d)this.d=g.opts.types[this.fillStyle].cloneNode(!1),this.ctx.appendChild(this.d);this.d.style.left=
this.x+"px";this.d.style.top=this.y+"px"}};var z,E=!1,F=!1,j=io.el("countdown"),o=0,K=150,c=[1,1,1,1],b=[0,0,0,1],p=[1,0,0,0],h=[1,0,0,1],s=[[c,h,h,h,h,h,c],[b,b,b,b,b,b,b],[c,b,b,c,p,p,c],[c,b,b,c,b,b,c],[h,h,h,c,b,b,b],[c,p,p,c,b,b,c],[c,p,p,c,h,h,c],[c,b,b,b,b,b,b],[c,h,h,c,h,h,c],[c,h,h,c,b,b,c]],J=[[2,2],[2,2],[1,2],[2,2],[1,2],[2,2],[2,2]],H=function(a){if(a.target.id=="logo"||a.target.className=="share"||a.target.className=="nav"){if(!A&&a.target.id=="logo")io.el("index").className="hactivated",
A=!0;else if(!A)return!0;var b=a.layerX||a.offsetX,c=a.layerY||a.offsetY,h=a.target.getAttribute("href"),f;a.target.className=="nav"?(f=a.target.parentNode.cloneNode(!0),j.appendChild(f),f.getElementsByTagName("a")[0].style.cursor="pointer",a.target.parentNode.parentNode.removeChild(a.target.parentNode)):(f=a.target.cloneNode(!1),j.appendChild(f),a.target.parentNode.removeChild(a.target),f.style.cursor="pointer");var i=f.offsetWidth,l=f.offsetHeight,m=!1;f.style.zIndex="99";f.style.position="absolute";
f.style.left=(a.pageX||a.clientX)-g.bounds[0]+b*-1+"px";f.style.top=(a.pageY||a.clientY)-g.bounds[1]+c*-1+"px";var G=function(a){f.style.left=(a.pageX||a.clientX)-g.bounds[0]+b*-1+"px";f.style.top=(a.pageY||a.clientY)-g.bounds[1]+c*-1+"px";g.createSurface(f.id,parseInt(f.style.left,0)+i/2,parseInt(f.style.top,0)+l/2,i/2,l/2);m=!0},n=function(a){io.unlisten("mousemove",document,G);io.unlisten("mouseup",document,n);if(m)a.preventDefault(),a.stopPropagation();else if(h)window.location.href=h;return!1};
io.listen("mousemove",document,G);io.listen("mouseup",document,n);a.stopPropagation();a.preventDefault();return!1}else return!0},I=(new Date(2012,4,10,9,0,0)).getTime(),n,l=[],m=[],y=C(),A;io.listen("resize",window,function(){y=C();g.updateBounds(r(j))});io.listen("unload",window,function(){m=n=l=null;g.unload();g=null});degraded||io.listen("mousedown",document,H);c=[];c.push({gravity:{x:-90,y:20},colors:["ff6f6f","ff6f6f","ff6f6f","","be0800","be0800","","ff6f6f","ff6f6f","","be0800","be0800"],surface:{density:0.1,
restitution:0,friction:0},dotType:"heart",dots:{density:0.1,restitution:0,friction:0,highVelocity:170,lowVelocity:90},bounds:r(j),behavior:w,condition:function(){var a=new Date;return a.getUTCMonth()==1&&(a.getUTCDate()==14&&a.getUTCHours()>=8||a.getUTCDate()==15&&a.getUTCHours()<8)},ctx:j});c.push({gravity:{x:-90,y:1E3},colors:["00994f","00994f","00994f","","9ece78","9ece78","","00994f","00994f","","9ece78","9ece78"],surface:{density:0.1,restitution:0,friction:0},dotType:"clover",dots:{density:0.1,
restitution:0,friction:0,highVelocity:170,lowVelocity:90},bounds:r(j),behavior:function(){document.getElementsByTagName("body")[0].className+="clover";w()},condition:function(){var a=new Date;return a.getUTCMonth()==2&&(a.getUTCDate()==17&&a.getUTCHours()>=8||a.getUTCDate()==18&&a.getUTCHours()<8)},ctx:j});c.push({gravity:{x:0,y:500},colors:["265897","265897","265897","","13acfa","13acfa","","c0000b","c0000b","","009a49","009a49"],dotType:"ball",surface:{density:1,restitution:1,friction:0},dots:{density:0.3,
restitution:0.5,friction:0.1,highVelocity:1500,lowVelocity:700},bounds:r(j),condition:function(){var a=new Date;return a.getUTCMonth()==3&&(a.getUTCDate()==1&&a.getUTCHours()>=8||a.getUTCDate()==2&&a.getUTCHours()<8)},behavior:function(){var a=!!document.createElement("audio").canPlayType,b=0;if(a){var c=navigator.product=="Gecko"?"ogg":"mp3",g=document.createElement("audio");g.src="static/punch."+c;g.preload="auto";g.volume=1;document.getElementsByTagName("body")[0].appendChild(g);var f=document.createElement("audio");
f.src="static/punch-go."+c;f.preload="auto";f.volume=1;document.getElementsByTagName("body")[0].appendChild(f)}var h=document.createElement("div");h.className="screen";h.style.opacity=0;h.style.filter="alpha(opacity=0)";document.getElementsByTagName("body")[0].appendChild(h);io.unlisten("mousedown",document,H);io.listen("click",io.el("logo"),function(i){i.preventDefault();if(b>1)return!1;if(b==1){if(F)return!1;if(a)f.src="static/punch-go."+c,f.play();E=!0;D=function(){for(var a=[],b=0;b<12;b++)b==
3||b==6||b==9?a.push(":"):a.push(Math.ceil(Math.random()*9));return a};clearInterval(z);z=setInterval(x,50);b++;setTimeout(function(){clearInterval(z);io.injectScript("static/js/1998.js");io.injectScript("static/js/1998-stars.js");F=!0},4E3)}else a&&g.play(),h.style.opacity=b+0.1+0.5,h.style.filter="alpha(opacity="+(b+0.1+0.5)*100+")",b++;return!1})},ctx:j});c.push({gravity:{x:0,y:400},colors:["265897","265897","265897","","13acfa","13acfa","","c0000b","c0000b","","009a49","009a49"],dotType:"ball",
surface:{density:1,restitution:1,friction:0},dots:{density:0.3,restitution:0.5,friction:0.1,highVelocity:1E3,lowVelocity:300},bounds:r(j),condition:function(){return!0},ctx:j});for(var g,b=0;b<c.length;b++)if(c[b].condition.call()===!0){g=new i(c[b]);c[b].behavior&&c[b].behavior.call();break}document.getElementsByTagName("body")[0].scrollTop=0;x()})();