/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.evernote.edam.type;

import java.util.Hashtable;
import java.util.Vector;
import java.util.Enumeration;

public class Constants {

  public static final String EDAM_NOTE_SOURCE_WEB_CLIP = "web.clip";

  public static final String EDAM_NOTE_SOURCE_MAIL_CLIP = "mail.clip";

  public static final String EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY = "mail.smtp";

}
