/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.evernote.edam.type;

/**
 * This enumeration defines the possible sort ordering for notes when
 * they are returned from a search result.
 */
public class NoteSortOrder implements org.apache.thrift.TEnum {

  public static final NoteSortOrder CREATED = new NoteSortOrder(1);
  public static final NoteSortOrder UPDATED = new NoteSortOrder(2);
  public static final NoteSortOrder RELEVANCE = new NoteSortOrder(3);
  public static final NoteSortOrder UPDATE_SEQUENCE_NUMBER = new NoteSortOrder(4);
  public static final NoteSortOrder TITLE = new NoteSortOrder(5);

  private final int value;

  private NoteSortOrder(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static NoteSortOrder findByValue(int value) { 
    switch (value) {
      case 1:
        return CREATED;
      case 2:
        return UPDATED;
      case 3:
        return RELEVANCE;
      case 4:
        return UPDATE_SEQUENCE_NUMBER;
      case 5:
        return TITLE;
      default:
        return null;
    }
  }
}
