/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Evernote.EDAM.NoteStore
{

  [Serializable]
  public partial class AdImpressions : TBase
  {
    private int adId;
    private int impressionCount;
    private int impressionTime;

    public int AdId
    {
      get
      {
        return adId;
      }
      set
      {
        __isset.adId = true;
        this.adId = value;
      }
    }

    public int ImpressionCount
    {
      get
      {
        return impressionCount;
      }
      set
      {
        __isset.impressionCount = true;
        this.impressionCount = value;
      }
    }

    public int ImpressionTime
    {
      get
      {
        return impressionTime;
      }
      set
      {
        __isset.impressionTime = true;
        this.impressionTime = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool adId;
      public bool impressionCount;
      public bool impressionTime;
    }

    public AdImpressions() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              this.adId = iprot.ReadI32();
              this.__isset.adId = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              this.impressionCount = iprot.ReadI32();
              this.__isset.impressionCount = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              this.impressionTime = iprot.ReadI32();
              this.__isset.impressionTime = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("AdImpressions");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.adId) {
        field.Name = "adId";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(this.adId);
        oprot.WriteFieldEnd();
      }
      if (__isset.impressionCount) {
        field.Name = "impressionCount";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(this.impressionCount);
        oprot.WriteFieldEnd();
      }
      if (__isset.impressionTime) {
        field.Name = "impressionTime";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(this.impressionTime);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("AdImpressions(");
      sb.Append("adId: ");
      sb.Append(this.adId);
      sb.Append(",impressionCount: ");
      sb.Append(this.impressionCount);
      sb.Append(",impressionTime: ");
      sb.Append(this.impressionTime);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
