/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Evernote.EDAM.NoteStore
{

  [Serializable]
  public partial class NoteCollectionCounts : TBase
  {
    private Dictionary<string, int> notebookCounts;
    private Dictionary<string, int> tagCounts;
    private int trashCount;

    public Dictionary<string, int> NotebookCounts
    {
      get
      {
        return notebookCounts;
      }
      set
      {
        __isset.notebookCounts = true;
        this.notebookCounts = value;
      }
    }

    public Dictionary<string, int> TagCounts
    {
      get
      {
        return tagCounts;
      }
      set
      {
        __isset.tagCounts = true;
        this.tagCounts = value;
      }
    }

    public int TrashCount
    {
      get
      {
        return trashCount;
      }
      set
      {
        __isset.trashCount = true;
        this.trashCount = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool notebookCounts;
      public bool tagCounts;
      public bool trashCount;
    }

    public NoteCollectionCounts() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                this.notebookCounts = new Dictionary<string, int>();
                TMap _map76 = iprot.ReadMapBegin();
                for( int _i77 = 0; _i77 < _map76.Count; ++_i77)
                {
                  string _key78;
                  int _val79;
                  _key78 = iprot.ReadString();
                  _val79 = iprot.ReadI32();
                  this.notebookCounts[_key78] = _val79;
                }
                iprot.ReadMapEnd();
              }
              this.__isset.notebookCounts = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Map) {
              {
                this.tagCounts = new Dictionary<string, int>();
                TMap _map80 = iprot.ReadMapBegin();
                for( int _i81 = 0; _i81 < _map80.Count; ++_i81)
                {
                  string _key82;
                  int _val83;
                  _key82 = iprot.ReadString();
                  _val83 = iprot.ReadI32();
                  this.tagCounts[_key82] = _val83;
                }
                iprot.ReadMapEnd();
              }
              this.__isset.tagCounts = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              this.trashCount = iprot.ReadI32();
              this.__isset.trashCount = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("NoteCollectionCounts");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.notebookCounts != null && __isset.notebookCounts) {
        field.Name = "notebookCounts";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.String, TType.I32, this.notebookCounts.Count));
          foreach (string _iter84 in this.notebookCounts.Keys)
          {
            oprot.WriteString(_iter84);
            oprot.WriteI32(this.notebookCounts[_iter84]);
            oprot.WriteMapEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      if (this.tagCounts != null && __isset.tagCounts) {
        field.Name = "tagCounts";
        field.Type = TType.Map;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.String, TType.I32, this.tagCounts.Count));
          foreach (string _iter85 in this.tagCounts.Keys)
          {
            oprot.WriteString(_iter85);
            oprot.WriteI32(this.tagCounts[_iter85]);
            oprot.WriteMapEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.trashCount) {
        field.Name = "trashCount";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(this.trashCount);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("NoteCollectionCounts(");
      sb.Append("notebookCounts: ");
      sb.Append(this.notebookCounts);
      sb.Append(",tagCounts: ");
      sb.Append(this.tagCounts);
      sb.Append(",trashCount: ");
      sb.Append(this.trashCount);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
