/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Evernote.EDAM.NoteStore
{

  [Serializable]
  public partial class NoteMetadata : TBase
  {
    private string guid;
    private string title;
    private int contentLength;
    private long created;
    private long updated;
    private int updateSequenceNum;
    private string notebookGuid;
    private List<string> tagGuids;
    private Evernote.EDAM.Type.NoteAttributes attributes;
    private string largestResourceMime;
    private int largestResourceSize;

    public string Guid
    {
      get
      {
        return guid;
      }
      set
      {
        __isset.guid = true;
        this.guid = value;
      }
    }

    public string Title
    {
      get
      {
        return title;
      }
      set
      {
        __isset.title = true;
        this.title = value;
      }
    }

    public int ContentLength
    {
      get
      {
        return contentLength;
      }
      set
      {
        __isset.contentLength = true;
        this.contentLength = value;
      }
    }

    public long Created
    {
      get
      {
        return created;
      }
      set
      {
        __isset.created = true;
        this.created = value;
      }
    }

    public long Updated
    {
      get
      {
        return updated;
      }
      set
      {
        __isset.updated = true;
        this.updated = value;
      }
    }

    public int UpdateSequenceNum
    {
      get
      {
        return updateSequenceNum;
      }
      set
      {
        __isset.updateSequenceNum = true;
        this.updateSequenceNum = value;
      }
    }

    public string NotebookGuid
    {
      get
      {
        return notebookGuid;
      }
      set
      {
        __isset.notebookGuid = true;
        this.notebookGuid = value;
      }
    }

    public List<string> TagGuids
    {
      get
      {
        return tagGuids;
      }
      set
      {
        __isset.tagGuids = true;
        this.tagGuids = value;
      }
    }

    public Evernote.EDAM.Type.NoteAttributes Attributes
    {
      get
      {
        return attributes;
      }
      set
      {
        __isset.attributes = true;
        this.attributes = value;
      }
    }

    public string LargestResourceMime
    {
      get
      {
        return largestResourceMime;
      }
      set
      {
        __isset.largestResourceMime = true;
        this.largestResourceMime = value;
      }
    }

    public int LargestResourceSize
    {
      get
      {
        return largestResourceSize;
      }
      set
      {
        __isset.largestResourceSize = true;
        this.largestResourceSize = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool guid;
      public bool title;
      public bool contentLength;
      public bool created;
      public bool updated;
      public bool updateSequenceNum;
      public bool notebookGuid;
      public bool tagGuids;
      public bool attributes;
      public bool largestResourceMime;
      public bool largestResourceSize;
    }

    public NoteMetadata() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              this.guid = iprot.ReadString();
              this.__isset.guid = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              this.title = iprot.ReadString();
              this.__isset.title = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.I32) {
              this.contentLength = iprot.ReadI32();
              this.__isset.contentLength = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I64) {
              this.created = iprot.ReadI64();
              this.__isset.created = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.I64) {
              this.updated = iprot.ReadI64();
              this.__isset.updated = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 10:
            if (field.Type == TType.I32) {
              this.updateSequenceNum = iprot.ReadI32();
              this.__isset.updateSequenceNum = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 11:
            if (field.Type == TType.String) {
              this.notebookGuid = iprot.ReadString();
              this.__isset.notebookGuid = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 12:
            if (field.Type == TType.List) {
              {
                this.tagGuids = new List<string>();
                TList _list60 = iprot.ReadListBegin();
                for( int _i61 = 0; _i61 < _list60.Count; ++_i61)
                {
                  string _elem62 = null;
                  _elem62 = iprot.ReadString();
                  this.tagGuids.Add(_elem62);
                }
                iprot.ReadListEnd();
              }
              this.__isset.tagGuids = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 14:
            if (field.Type == TType.Struct) {
              this.attributes = new Evernote.EDAM.Type.NoteAttributes();
              this.attributes.Read(iprot);
              this.__isset.attributes = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 20:
            if (field.Type == TType.String) {
              this.largestResourceMime = iprot.ReadString();
              this.__isset.largestResourceMime = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 21:
            if (field.Type == TType.I32) {
              this.largestResourceSize = iprot.ReadI32();
              this.__isset.largestResourceSize = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("NoteMetadata");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.guid != null && __isset.guid) {
        field.Name = "guid";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(this.guid);
        oprot.WriteFieldEnd();
      }
      if (this.title != null && __isset.title) {
        field.Name = "title";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(this.title);
        oprot.WriteFieldEnd();
      }
      if (__isset.contentLength) {
        field.Name = "contentLength";
        field.Type = TType.I32;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(this.contentLength);
        oprot.WriteFieldEnd();
      }
      if (__isset.created) {
        field.Name = "created";
        field.Type = TType.I64;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(this.created);
        oprot.WriteFieldEnd();
      }
      if (__isset.updated) {
        field.Name = "updated";
        field.Type = TType.I64;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(this.updated);
        oprot.WriteFieldEnd();
      }
      if (__isset.updateSequenceNum) {
        field.Name = "updateSequenceNum";
        field.Type = TType.I32;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(this.updateSequenceNum);
        oprot.WriteFieldEnd();
      }
      if (this.notebookGuid != null && __isset.notebookGuid) {
        field.Name = "notebookGuid";
        field.Type = TType.String;
        field.ID = 11;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(this.notebookGuid);
        oprot.WriteFieldEnd();
      }
      if (this.tagGuids != null && __isset.tagGuids) {
        field.Name = "tagGuids";
        field.Type = TType.List;
        field.ID = 12;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, this.tagGuids.Count));
          foreach (string _iter63 in this.tagGuids)
          {
            oprot.WriteString(_iter63);
            oprot.WriteListEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      if (this.attributes != null && __isset.attributes) {
        field.Name = "attributes";
        field.Type = TType.Struct;
        field.ID = 14;
        oprot.WriteFieldBegin(field);
        this.attributes.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (this.largestResourceMime != null && __isset.largestResourceMime) {
        field.Name = "largestResourceMime";
        field.Type = TType.String;
        field.ID = 20;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(this.largestResourceMime);
        oprot.WriteFieldEnd();
      }
      if (__isset.largestResourceSize) {
        field.Name = "largestResourceSize";
        field.Type = TType.I32;
        field.ID = 21;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(this.largestResourceSize);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("NoteMetadata(");
      sb.Append("guid: ");
      sb.Append(this.guid);
      sb.Append(",title: ");
      sb.Append(this.title);
      sb.Append(",contentLength: ");
      sb.Append(this.contentLength);
      sb.Append(",created: ");
      sb.Append(this.created);
      sb.Append(",updated: ");
      sb.Append(this.updated);
      sb.Append(",updateSequenceNum: ");
      sb.Append(this.updateSequenceNum);
      sb.Append(",notebookGuid: ");
      sb.Append(this.notebookGuid);
      sb.Append(",tagGuids: ");
      sb.Append(this.tagGuids);
      sb.Append(",attributes: ");
      sb.Append(this.attributes== null ? "<null>" : this.attributes.ToString());
      sb.Append(",largestResourceMime: ");
      sb.Append(this.largestResourceMime);
      sb.Append(",largestResourceSize: ");
      sb.Append(this.largestResourceSize);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
