# File:		Makefile fuer freiesMagazin-Programmierwettbewerb
# Author:	Dominik Wagenfuehr
#

# implementation
all:
	cd fm-game && make && cd ../fm-ai && make && cd ..

clean:
	cd fm-game && make clean && cd ../fm-ai && make clean && cd ..





