/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Evernote.EDAM.Error
{

  [Serializable]
  public partial class EDAMNotFoundException : Exception, TBase
  {
    private string identifier;
    private string key;

    public string Identifier
    {
      get
      {
        return identifier;
      }
      set
      {
        __isset.identifier = true;
        this.identifier = value;
      }
    }

    public string Key
    {
      get
      {
        return key;
      }
      set
      {
        __isset.key = true;
        this.key = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool identifier;
      public bool key;
    }

    public EDAMNotFoundException() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              this.identifier = iprot.ReadString();
              this.__isset.identifier = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              this.key = iprot.ReadString();
              this.__isset.key = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("EDAMNotFoundException");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.identifier != null && __isset.identifier) {
        field.Name = "identifier";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(this.identifier);
        oprot.WriteFieldEnd();
      }
      if (this.key != null && __isset.key) {
        field.Name = "key";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(this.key);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("EDAMNotFoundException(");
      sb.Append("identifier: ");
      sb.Append(this.identifier);
      sb.Append(",key: ");
      sb.Append(this.key);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
