/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.evernote.edam.error;

import java.util.Vector;
import java.util.Hashtable;
import java.util.Enumeration;
import org.apache.thrift.*;

public class Constants {

}
